---
kind: Service
apiVersion: v1
metadata:
  name: dataretrievalservice
spec:
  selector:
    app: data-retrieval
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 3006
      # Port to forward to inside the pod
      targetPort: 5012
      # Port accessible outside cluster
      nodePort: 30006
  type: LoadBalancer
  type: LoadBalancer
 
 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: data-retrieval-deployment
spec:
  selector:
    matchLabels:
      app: data-retrieval
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: data-retrieval
    spec:
      containers:
      - name: data-retrieval
        image: orenda15/data_retrieval
---

  apiVersion: "security.istio.io/v1beta1"
  kind: "PeerAuthentication"
  metadata:
    name: data-retrieval-authentication
    
  spec:
    selector:
      matchLabels:
        app: data-retrieval
    mtls:
      mode: STRICT
              
