apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-retrieval
  labels:
    app: data-retrieval
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: data-retrieval
  template:
    metadata:
      labels:
        app: data-retrieval
    spec:
      containers:
      - name: data-retrieval
        image: orenda15/data-retrieval:9a30ef79fc57e4200423ea62e72093117afa716d
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3006
          protocol: TCP
        # resources:
        #   limits:
        #     cpu: 2000m
        #     memory: 512Mi
        #   requests:
        #     cpu: 100m
        #     memory: 64Mi